#!/bin/bash
# (SPDX-License-Identifier: MIT)
#
# Hook script to do something after repo checkout.
# Called by "git pull/checkout" with arguments
#
# To enable this hook, rename this file to "post-merge".
#
# This script will decrypt secret files if it's possible.
# See README-secretsencrypton.md for more info.

# Enable global debug
# set -xv

set -uo pipefail
export ERROR_CODE=0
export TMP_FILE="$(mktemp)"
export TMP_DIR="$(mktemp -d)"

trap cleanup EXIT SIGHUP SIGINT SIGQUIT SIGTERM

function cleanup() {
    rm -fr "$TMP_FILE"
    rm -fr "$TMP_DIR"
    exit $ERROR_CODE
}

# Source common functions
. $(dirname $0)/global_functions.sh

function postmerge_encryption_check() {
    local files_to_merge
    local files_to_decrypt
    local config_filename
    local file_pattern
    if [ "${1+x}" == "x" ]; then
        config_filename=$1
    else
        config_filename=".secretsencryption-sops.yaml"
    fi

    files_to_merge=$(git --no-pager diff --name-only HEAD@{0} HEAD@{1})
    # debug "Pulled files:\n${files_to_merge}\n\n"

    if [ -f "$config_filename" ]; then
        file_pattern="($(yq '.creation_rules.[].path_regex' $config_filename | grep -v null | tr '\n' '|' | sed -E 's/\|$//'))"
        if [ -z "${file_pattern}" ]; then
            cat <<EOF

Warning: $(pwd)/$config_filename file not found and/or
'path_regex:' in it is not set.
NOTHING IS DECRYPTED

See README-secretsencrypton.md for more info.
See also SOPS documentation: https://getsops.io/docs/

Disable commit encryption and get rid of this message using:

    git config --global hooks.secretsencrypton "none"

Use --local option to skip encryption for this repository only.
EOF
            exit 1
        fi

        files_to_decrypt=$(git --no-pager diff --name-only HEAD@{0} HEAD@{1} | grep -E ${file_pattern} | grep -vE 'sops.yaml$')
        debug "Files to decrypt:\n${files_to_decrypt}\n\n"

        for file in $files_to_decrypt; do
            # Update file status in .gitattributes
            # Remove before add to ensure single entry with latest configuration
            remove_from_gitattributes "$file"
            add_to_gitattributes "$file"
            [ $REP_LOCKED -eq 1 ] && continue # Do not decrypt -- files are normally encrypted in working tree
            is_encrypted "${file}"
            status=$?
            if [ $status -eq 0 ]; then
                debug "$file is encrypted and can be decrypted\n"
                msg "Decrypting ${file}..."
                sops -d -i "${file}"
            elif [ $status -eq 1 ]; then
                debug "$file is encrypted but cannot be decrypted. Do it manually.\n"
                echo "$file last committed by $(git --no-pager shortlog -1 -ces -- $file)" >> "${TMP_FILE}"
            else
                debug "$file is not encrypted\n"
            fi
        done
    fi
}

args="$*"
# Redirect output to stderr.
exec 1>&2

# https://github.com/timaliev/git-secrets-encryption/issues/3
VERBOSE=0
check_debug
check_lock

debug "TMP_DIR=$TMP_DIR\n"
debug "TMP_FILE=$TMP_FILE\n"

msg "Running post-merge check..."
debug "Args=$args\n"

secretsencrypton=$(git config hooks.secretsencrypton | tr '[:lower:]' '[:upper:]')
if [ "${secretsencrypton}" != "NONE" ]; then
    if [ -z "$secretsencrypton" ]; then
        cat <<EOF

Warning: Git config hooks.secretsencrypton is not set but post-checkout hook installed.
NOTHING IS DECRYPTED, COMMIT ENCRYPTION IS DISABLED.
Use appropriate tools to decrypt secrets manually, if any.

If you don't want to use auto secrets encryption during commit and
want to get rid of this message, set:

    git config hooks.secretsencrypton "none"

Otherwise set hooks.secretsencrypton to one of:

    "sops-inline"

Use --global option for secrets encryption enabled by default.
See README-secretsencrypton.md for more info.
EOF
    elif [ "${secretsencrypton}" == "SOPS-INLINE" ]; then
        debug "hooks.secretsencrypton is set to 'sops-inline'\n"
        postmerge_encryption_check
    else
        cat <<EOF

Warning: Git config hooks.secretsencrypton is set to: $(git config hooks.secretsencrypton)
This option is not implemented or supported.

NOTHING IS DECRYPTED, COMMIT ENCRYPTION IS DISABLED.
Use appropriate tools to decrypt secrets manually, if any.

Valid values for git config are:

    "none"
    "sops-inline"

Set this config variable using:

    git config hooks.secretsencrypton

Use --global option for secrets encryption enabled by default.
See README-secretsencrypton.md for more info.
EOF
    fi
fi

undecrypted_files=$(cat ${TMP_FILE})
if [ -n "${undecrypted_files}" ]; then
    msg "The following files are encrypted but cannot be decrypted on this system:\n"
    msg "${undecrypted_files}\n"
    msg "Please, decrypt them manually or contact with the last encrypted commit author."
fi

exit 0